config/routes.rb
Blog::Application.routes.draw do

  controller :sessions do
  get 'login' => :new
  post 'login' => :create
  delete 'logout' => :destroy
end

  resources :users do
    member do
      get :welcome
    end
  end

  resources :posts do
    member do
      get :comment
    end
    resources :comments
  end

   root :to => "posts#index"

end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
  attr_accessible :name, :email, :hashed_password, :hashed_password_confirmation
  attr_accessor :hashed_password_confirmation
  has_many :posts, :dependent => :destroy
  has_many :comments, :dependent => :destroy
    validates_confirmation_of :hashed_password, :if=>:password_changed?
    validates :hashed_password, :presence => true
    validates :name, :presence => true
    validates :email, :presence => true
    validates_uniqueness_of :email
    validates_format_of :email, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i, :message => "Invalid email"  
    
    validates :hashed_password_confirmation, :presence => true
    

    before_save :hash_password, :if => :password_changed?

    def password_changed?
      self.hashed_password.present?
    end

    def self.authenticate(email, password)
      # Because we use bcrypt we can't do this query in one part, first
      # we need to fetch the potential user
      
      if user = find_by_email(email)
        # Then compare the provided password against the hashed one in the db.
       
        if BCrypt::Password.new(user.hashed_password).is_password? password
          # If they match we return the user 
          return user
        end
      end
      # If we get here it means either there's no user with that email, or the wrong
      # password was provided.  But we don't want to let an attacker know which. 
      return nil
    end

private
    # This is where the real work is done, store the BCrypt has in the
    # database
    def hash_password
      self.hashed_password = BCrypt::Password.create(self.hashed_password)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json

  before_filter :admin_required, :only=>['index', 'edit', 'destroy']
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    @user.admin = 0

    respond_to do |format|
      if @user.save
        Welcomer.welcome(@user).deliver
        format.html { redirect_to posts_path, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to posts_path, :notice => 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def welcome
    userid = current_user
    @user = User.find(userid)
    @posts = @user.posts
    respond_to do |format|
      format.html
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :hashed_password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :hashed_password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div id="header_container">
<div id="header">
<h1>Editing user</h1>
</div>
</div>

<%= render 'form' %>

<%= link_to 'Show', @user %>
<%= link_to 'Back', welcome_user_path(:id => @user.id) %>

app/views/users/index.html.erb
<div id="header_container">
<div id="header">
<h1>Listing users</h1>
</div>
</div>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div id="header_container">
<div id="header">
<h1>New user</h1>
</div>
</div>

<%= render 'form' %>
<% if session[:user_id] %>
<% user = User.find(session[:user_id]) %>
<%= link_to 'Back', welcome_user_path(:id => user.id) %>
<% else %>
<%= link_to 'Back', posts_path %>
<% end %>

<div id = "loginstuff" style="">
<% if session[:user_id] == nil %>
<%= link_to 'Login', :controller => "sessions", :action => "new" %>
<%= link_to 'New User? Signup!', new_user_path %>
<% end %> 
<div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>



<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', welcome_user_path(:id => @user.id) %>

app/views/users/welcome.html.erb
<div id="header_container">
<!-- <div id="header">
  <h3>Welcome <%= @user.name %>, </h3>
</div> -->

<div id = "useroptions">
<%= link_to 'New Post', new_post_path %>
<%= link_to 'Change password', edit_user_path(:id => @user.id) %>
<%= link_to 'All Posts', :controller => "posts", :action => "index" %>
</div>

</div>
<div style="color: #FFFFFF;
    font: 18px Georgia,Utopia,'Palatino Linotype',Palatino,serif;
    margin: 0.5em 0;
    text-transform: none;">
<h3>Listing all posts by you </h3>
</div>

<div style="position:relative;left:10%;">
<% @posts.each do |post| %>
    <p><i><%= post.name %></i></p>

      <div id ="post_list">
    <table style="width:550px;border-bottom-style:dotted;">
        <tr>
          <td class="list_description" colspan="2">
      	   <dl>
      	     <dt><%= post.title %></dt>
             <br/>
      	     <dd><%= truncate(strip_tags(post.content), :length => 200) %></dd>
      	   </dl>
          </td>
        </tr>
        <tr>
          <td class="list_actions" style="text-align:left"><%= link_to 'Show', post %><br/>
          <% if session[:user_id] == @user.id %>
          <%= link_to 'Edit', edit_post_path(post) %><br\>
          <%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %></td>
          <% end %>
          <% time = Time.now - post.created_at %>
          <% hour = (time/3600).round %>
          <% seconds = time - hour*3600 %>
          <% minutes = (seconds/60).round %>
          <% if minutes < 0 %>
          <% minutes = minutes + 60 %>
          <% hour = hour - 1 %>
          <% end %>
          <td style="text-align:right;font-size: 70%">Posted <%= hour %> hours and <%= minutes %> minutes ago </td>
        </tr>
      </div>

        <br/>
  </table>
<% end %>